name: Pytest Report
on:
  workflow_run:
    workflows: [Pytest]
    types: [completed]
permissions:
    checks: write
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: actions/download-artifact@v6
        with:
          name: pytest-report
          run-id: ${{ github.event.workflow_run.id }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: pytest.xml
          comment: true
          pr_id: ${{ github.event.workflow_run.pull_requests[0].number }}